---
- name: create systemd service for managing swarm leaders
  sudo: yes
  template:
    dest: /usr/lib/systemd/system/swarm-leader.service
    src: swarm-leader.service.j2
  notify:
    - reload systemd

- name: enable and start the swarm-leaders
  sudo: yes
  service:
    name: swarm-leader
    enabled: yes
    state: restarted
